joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000  # in Hz

joint_position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - F_joint_1
    - F_joint_2
    - F_joint_3
    - F_joint_4
    - F_joint_5
    - F_joint_6
    - F_joint_7
  state_publish_rate: 1000

joint_torque_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - F_joint_1
    - F_joint_2
    - F_joint_3
    - F_joint_4
    - F_joint_5
    - F_joint_6
    - F_joint_7
  gains:
    F_joint_1: { p: 3000, i: 10.0, d: 50.0,  i_clamp: 320, antiwindup: true } # Parameter for simulation
    F_joint_2: { p: 4000, i: 50.0, d: 50.0, i_clamp: 320, antiwindup: true } # Parameter for simulation
    F_joint_3: { p: 1800,  i: 10.0, d: 10.0,  i_clamp: 176, antiwindup: true } # Parameter for simulation
    F_joint_4: { p: 1500, i: 10.0, d: 50.0, i_clamp: 176, antiwindup: true } # Parameter for simulation
    F_joint_5: { p: 1200,  i: 1.0, d: 10.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
    F_joint_6: { p: 1000,  i: 1.0, d: 5.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
    F_joint_7: { p: 1000,  i: 0.5, d: 3.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
  state_publish_rate: 1000

bspline_joint_trajectory_controller:
  type: joint_trajectory_controller/IBSplineJointTrajectoryController
  joints:
    - F_joint_1
    - F_joint_2
    - F_joint_3
    - F_joint_4
    - F_joint_5
    - F_joint_6
    - F_joint_7
  gains:
    F_joint_1: { p: 3000, i: 10.0, d: 50.0,  i_clamp: 320, antiwindup: true } # Parameter for simulation
    F_joint_2: { p: 3000, i: 50.0, d: 50.0, i_clamp: 320, antiwindup: true } # Parameter for simulation
    F_joint_3: { p: 1800,  i: 10.0, d: 10.0,  i_clamp: 176, antiwindup: true } # Parameter for simulation
    F_joint_4: { p: 1500, i: 10.0, d: 50.0, i_clamp: 176, antiwindup: true } # Parameter for simulation
    F_joint_5: { p: 1200,  i: 1.0, d: 10.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
    F_joint_6: { p: 1000,  i: 1.0, d: 5.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
    F_joint_7: { p: 1000,  i: 0.5, d: 3.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation

  state_publish_rate: 1000

bspline_ff_kino_joint_trajectory_controller:
  type: feedforward_controllers/BSplineFFKinoJointTrajectoryController
  joints:
    - F_joint_1
    - F_joint_2
    - F_joint_3
    - F_joint_4
    - F_joint_5
    - F_joint_6
    - F_joint_7
  gains:
    F_joint_1: { p: 3000, i: 10.0, d: 50.0,  i_clamp: 320, antiwindup: true } # Parameter for simulation
    F_joint_2: { p: 3000, i: 50.0, d: 50.0, i_clamp: 320, antiwindup: true } # Parameter for simulation
    F_joint_3: { p: 1800,  i: 10.0, d: 10.0,  i_clamp: 176, antiwindup: true } # Parameter for simulation
    F_joint_4: { p: 1500, i: 10.0, d: 50.0, i_clamp: 176, antiwindup: true } # Parameter for simulation
    F_joint_5: { p: 1200,  i: 8.0, d: 10.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
    F_joint_6: { p: 1000,  i: 2.0, d: 5.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
    F_joint_7: { p: 1000,  i: 2.0, d: 3.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
    #F_joint_5: { p: 1200,  i: 1.0, d: 10.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
    #F_joint_6: { p: 1000,  i: 1.0, d: 5.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
    #F_joint_7: { p: 1000,  i: 0.5, d: 3.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation

  state_publish_rate: 1000